### ISSUE TITLE
Create Features Page

### ISSUE THREAD

**Issue by seanbsu** [seanbsu/ChartCare#31]
# Create the Features Page

The purpose of this page is to give a more detailed description of the plans and their associated features.

## TODO

- [ ] Create the initial view page for layout and design
  - [ ] Define the layout and structure of the page
  - [ ] Implement the design using HTML and CSS in the razor page
  - [ ] Add placeholders for plan descriptions and features

- [ ] Populate the page with descriptions and features from the database
  - [ ] Fetch plan descriptions from the database using the service layer
  - [ ] Fetch associated features for each plan from the database using the service layer
  - [ ] set the data in the Home controller
  - [ ] populate the razor page with the data
