### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by seanbsu** [seanbsu/ChartCare#32]
# Update Documentation
Documentation for contributors needs to be updated to reflect the project structure and changes in the database.

## TODO

- [x] Update the  [contributing](./docs/contributing.md) doc and the [Technical Overview](./docs/TechnicalOverview.md) doc  to reflect the changes in the project structure.(e.g using a service layer to encapsulate business logic) some changes to note include:
   - [x] Populate the page with descriptions and features from the database
   - [x] service layers should include an interface for any new service
   - [x] after service concrete class is created it should be added to the project with dependency injection in Program.cs
   - [x] add service to the constructor of the controller that will use it
   - [x] add service to as a field to the controller that will use it
- [x] Update the .mwb file in /docs to reflect the core database tables
- [x] Update the database Schema image in /docs with a new captured image that reflects the current database
